feat(gpu): add `gpu` support for resnet + reproduce accuracy

diff --git a/halut b/halut
--- a/halut
+++ b/halut
@@ -63,11 +63,11 @@ version() {
 compare_conda_env() {
   default_name="halutmatmul"
 
-  if [ $default_name == $CONDA_DEFAULT_ENV ]; then
+  if [[ $CONDA_DEFAULT_ENV == *"halutmatmul"* ]]; then
     echo "[INFO] Conda env is activated ✅"
   else
-    echo "[ERROR] Activate conda env halutmatmul ❌"
-    exit $1
+    echo "[ERROR] Activate conda env halutmatmul ❌, ($CONDA_DEFAULT_ENV)"
+    exit 1
   fi
 }
 
